version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    assignees:
      - dmage
    groups:
      k8s:
        patterns:
          - k8s.io/*
          - sigs.k8s.io/*
